name: CI
on: [push]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Install Pandoc
        run: |
          sudo wget https://github.com/jgm/pandoc/releases/download/3.1.9/pandoc-3.1.9-1-amd64.deb
          sudo dpkg -i pandoc-3.1.9-1-amd64.deb

      - name: Install Tippecanoe
        run: |
          sudo apt-get update
          sudo apt-get install build-essential libsqlite3-dev zlib1g-dev
          git clone --depth 1 --branch 2.37.1 https://github.com/felt/tippecanoe.git
          cd tippecanoe
          make -j
          MANDIR=discard make install

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 21.x

      - uses: actions/checkout@v3

      - name: Run yarn install
        run: yarn install

      - name: Run yarn ci
        run: yarn ci
