name: CI
on: [push]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 21.x

      - name: Install Pandoc
        run: |
          sudo apt-get update

      - name: Install Pandoc v3
        run: sudo wget https://github.com/jgm/pandoc/releases/download/3.1.9/pandoc-3.1.9-1-amd64.deb && sudo dpkg -i pandoc-3.1.9-1-amd64.deb

      - name: Run yarn install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install`

      - name: Run yarn ci
        uses: borales/actions-yarn@v4
        with:
          cmd: ci # will run `yarn ci`
