name: CI
on: [push]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 21.x

      - name: Install Pandoc
        run: |
          sudo apt-get update
          - name: Install Pandoc v3
            run: |
              sudo apt-get update
              sudo apt-get install -y pandoc=3.x.x

      - name: Run yarn install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install`

      - name: Run yarn ci
        uses: borales/actions-yarn@v4
        with:
          cmd: ci # will run `yarn ci`
